In [21]:
import tensorflow as tf

In [22]:
import numpy as np

In [23]:
x_data = np.array([[0,0],[1,0],[1,1],[0,0],[0,0],[0,1]])
y_data = np.array([[1,0,0],[0,1,0],[0,0,1],[1,0,0],[1,0,0],[0,0,1]])

In [24]:
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [25]:
W = tf.Variable(tf.random_uniform([2,3],-1.,1.))
b = tf.Variable(tf.zeros([3]))

In [26]:
L = tf.add(tf.matmul(X,W),b)
L = tf.nn.relu(L)

In [27]:
model = tf.nn.softmax(L)

In [28]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(model),axis=1))

In [29]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)

In [30]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [36]:
for i in range(100):
    sess.run(train_op,feed_dict={X:x_data,Y:y_data})
    if i%10 == 0:
        print(
            "cost:",sess.run(cost,feed_dict={X:x_data,Y:y_data}),
            "\nW:",sess.run(W,feed_dict={X:x_data,Y:y_data}),
            "\nb:",sess.run(b,feed_dict={X:x_data,Y:y_data})
        )

cost: 0.946184 
W: [[-0.19483805 -0.09379983 -0.38064653]
 [-0.74103737 -0.89754987  0.9995056 ]] 
b: [0.         0.         0.00033898]
cost: 0.9430108 
W: [[-0.19483805 -0.09379983 -0.37205225]
 [-0.74103737 -0.89754987  1.0151347 ]] 
b: [0.         0.         0.00096036]
cost: 0.939905 
W: [[-0.19483805 -0.09379983 -0.36355716]
 [-0.74103737 -0.89754987  1.030603  ]] 
b: [0.         0.         0.00142371]
cost: 0.936841 
W: [[-0.19483805 -0.09379983 -0.35516298]
 [-0.74103737 -0.89754987  1.0459065 ]] 
b: [0.000000e+00 0.000000e+00 5.135694e-05]
cost: 0.93386173 
W: [[-0.19483805 -0.09379983 -0.3468666 ]
 [-0.74103737 -0.89754987  1.061051  ]] 
b: [0.         0.         0.00018786]
cost: 0.9309438 
W: [[-0.19483805 -0.09379983 -0.33866704]
 [-0.74103737 -0.89754987  1.0760385 ]] 
b: [0.         0.         0.00016833]
cost: 0.9280865 
W: [[-0.19483805 -0.09379983 -0.33056384]
 [-0.74103737 -0.89754987  1.0908692 ]] 
b: [ 0.00000e+00  0.00000e+00 -8.51728e-06]
cost: 0.92531776 
W: [[-

In [48]:
print(sess.run(model,feed_dict={X:x_data,Y:y_data}))
prediction = tf.argmax(model,axis=1)
sess.run(prediction,feed_dict={X:x_data,Y:y_data})

[[0.33318326 0.33318326 0.33363348]
 [0.33333334 0.33333334 0.33333334]
 [0.23058902 0.23058902 0.538822  ]
 [0.33318326 0.33318326 0.33363348]
 [0.33318326 0.33318326 0.33363348]
 [0.19403182 0.19403182 0.61193633]]


array([2, 0, 2, 2, 2, 2], dtype=int64)

In [50]:
target = tf.argmax(Y,axis=1)
print("예측값:",sess.run(prediction,feed_dict={X:x_data,Y:y_data}))
print("실제값:",sess.run(target,feed_dict={X:x_data,Y:y_data}))

예측값: [2 0 2 2 2 2]
실제값: [0 1 2 0 0 2]


In [51]:
is_correct = tf.equal(prediction,target)
accurarcy = tf.reduce_mean(tf.cast(is_correct,tf.float32))
print("정확도: %.2f" %sess.run(accurarcy*100,feed_dict={X:x_data,Y:y_data}))

정확도: 33.33
